### ISSUE TITLE
error: 0x7fce5eeb1ce6 caffe::ConvolutionDepthwiseLayer<>::LayerSetUp()

### ISSUE THREAD

**Issue by JasmineAIGC** [farmingyard/caffe-mobilenet#11]
hi，
    I'm modifying a network with mobilenet in caffe. At the time of training, an error occurred, as fellows: 

.......

> I1205 23:51:29.949239 21979 net.cpp:84] Creating Layer conv1_2/dw
> I1205 23:51:29.949245 21979 net.cpp:406] conv1_2/dw <- conv1_1
> I1205 23:51:29.949250 21979 net.cpp:380] conv1_2/dw -> conv1_2/dw
> 
> > * Aborted at 1512489089 (unix time) try "date -d @1512489089" if you are using GNU date ***
> > PC: @     0x7fce5eeb1ce6 caffe::ConvolutionDepthwiseLayer<>::LayerSetUp()
> > *** SIGSEGV (@0x0) received by PID 21979 (TID 0x7fce5fc019c0) from PID 0; stack trace: ***
> 
>     @     0x7fce48883370 (unknown)
>     @     0x7fce5eeb1ce6 caffe::ConvolutionDepthwiseLayer<>::LayerSetUp()
>     @     0x7fce5eec3b1c caffe::Net<>::Init()
>     @     0x7fce5eec5772 caffe::Net<>::Net()
>     @     0x7fce5eed5008 caffe::Solver<>::InitTrainNet()
>     @     0x7fce5eed5f53 caffe::Solver<>::Init()
>     @     0x7fce5eed622f caffe::Solver<>::Solver()
>     @     0x7fce5eeecb11 caffe::Creator_SGDSolver<>()
>     @           0x41224e caffe::SolverRegistry<>::CreateSolver()
>     @           0x40a778 train()
>     @           0x40817c main
>     @     0x7fce484d4b35 __libc_start_main
>     @           0x408a61 (unknown)

the correspondence position in prototxt: 
......

> #conv1_2
> layer {
>   name: "conv1_2/dw"
>   type: "ConvolutionDepthwise"
>   bottom: "conv1_1"
>   top: "conv1_2/dw"
>   param {
>     lr_mult: 1.0
>     decay_mult: 1
>   }
>   param {
>     lr_mult: 2.0
>     decay_mult: 0
>   }
>   convolution_param {
>     num_output: 64
>     pad: 1
>     kernel_size: 3
>     weight_filler {
>       type: "msra"
>       # std: 0.01
>     }
>     bias_filler {
>       type: "constant"
>       value: 0.2
>     }
>   }
> }

......

the .cpp/.cu files have been put in 'caffe/src/caffe/layers', and .hpp put in 'caffe/include/caffe/layers', I did not do other changes. 
So, can you give me some comments about this error? 
thank you!
@farmingyard

**Comment by notabigfish** [comment]
@Jasmine66Bloom Hi, I met the same error. How did you solve this? Thank you !
