### ISSUE TITLE
Memory on gpu consumed when training is too big.

### ISSUE THREAD

**Issue by leon-liangwu** [farmingyard/caffe-mobilenet#3]
About 8GB for a 5.2M model, is that too weird？

**Comment by guo253** [comment]
Maybe you can turn off the cudnn option.

**Comment by jnulzl** [comment]
@DreamHorse0301 try "engine: CAFFE" in dw layer

**Comment by leon-liangwu** [comment]
@jnulzl  @guo253  Thans and yes, I have solved it by set engine type. Sorry for forget to close this issue.
